### ISSUE TITLE
Description of app & sketch

### ISSUE THREAD

**Issue by ajuliettet** [UBC-MDS/video_game_sales_dashboard#11]
Let's meet and discuss Thursday 7pm!

**Comment by ajuliettet** [comment]
Here is my first draft. 
![IMG_8665](https://user-images.githubusercontent.com/69942794/154576376-7c3fd572-955f-49b3-8a9c-9f756692f582.JPG)

**Comment by MaeveShi** [comment]
![IMG_4994](https://user-images.githubusercontent.com/59086617/154590168-78315546-7c45-44c9-9644-ded6345a2c4a.jpg)

**Comment by MaeveShi** [comment]
![draft](https://user-images.githubusercontent.com/59086617/154591510-8bb30491-3ab1-4094-b89e-6764ea3cf32d.jpg)

**Comment by alexYinanGu0** [comment]
![unnamed](https://user-images.githubusercontent.com/75028436/154598880-c70c31ce-bbe2-4549-a1dc-e11f63a7e096.jpg)
